### ISSUE TITLE
Improve static assert reporting for GetObjectType() in 32 bit environment

### ISSUE THREAD

**Issue by artem-lunarg** [KhronosGroup/Vulkan-Utility-Libraries#221]
`template<typename T> VkObjectType GetObjectType()`

It is implemented for 64 bit environment (`VK_USE_64_BIT_PTR_DEFINES`) but there is also a default specialization which is enabled both in 32/64 bits:
```
template<typename T> VkObjectType GetObjectType() {
    static_assert(sizeof(T) == 0, "GetObjectType() is being used with an unsupported Type! Is the code-gen up to date?");
    return VK_OBJECT_TYPE_UNKNOWN;
}
```

when used in 32 bit mode this error message is confusing. The suggestion is to have a separate static assert for 32 bit that will say `GetObjectType<>` template is not supported and then the above version for 64 bit that will detect unsupported types.

**Comment by charles-lunarg** [comment]
I feel like the solution is to create two implementations of the default specialization, one for 32 bit and 64 bit. The 64 bit is the current one, but the 32 bit one is "GetObjectType() does not work in 32 bit builds".

Unless you have a better idea, that would be how I would fix it. 32 bit vulkan headers are unfortunately difficult due to the lack of typing for handle types.

**Comment by artem-lunarg** [comment]
@charles-lunarg that sounds like a good solution.
