### ISSUE TITLE
Add chromium build to CI

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Utility-Libraries#80]
Avoid issues like this:
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/81

**Comment by juan-lunarg** [comment]
FYI @charles-lunarg / @mikes-lunarg

**Comment by juan-lunarg** [comment]
Higher priority since these seems to routinely cause issues:
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/94

**Comment by christophe-lunarg** [comment]
It seems to me that this issue is more a case of warning levels or -WERROR not being high enough on Vulkan-Utility-Libraries by default, so including on developer system, and consistently across our repositories.

Adding chromium to C.I. might solve the issue for chromium but does it really resolves the issue ecosystem wise, I would say no and that increases our C.I. workload and impact our productivity.

**Comment by mikes-lunarg** [comment]
Happened again #113
